### DISCUSSION TITLE
Verilog build failed when using multistring description

### DISCUSSION THREAD

**Discussion by iDoka** [esynr3z/corsair#131] [Questions]
csrconfig:
```ini
[globcfg]
base_address  = 0
data_width    = 16
address_width = 8
register_reset = async_neg
address_increment = none
address_alignment = none
force_name_case = none
regmap_path = exam.yaml

[v_module]
generator = Verilog
path = exam.v
read_filler = 0
interface = lb
```

exam.yaml:
```yaml
regmap:
-   name: EXAM
    description: Examinate
    address: 1
    bitfields:
    -   name: exam
        description: |
            Examinate multistring values in yaml:
            0 - disable
            1 - enable
        reset: 0
        width: 1
        lsb: 0
        access: wo
        hardware: o
        enums: []
    -   name: none
        description: none description
        reset: 0
        width: 1
        lsb: 1
        access: rw
        hardware: io
        enums: []
```

exam.v:
```verilog
...
//---------------------
// Bit field:
// EXAM[0] - exam - Examinate multistring values in yaml:
0 - disable
1 - enable

// access: wo, hardware: o
//---------------------
...
```

Syntax check:
```bash
verible-verilog-syntax playground/exam.v

playground/exam.v:51:1: syntax error at token "0"
playground/exam.v:52:1: syntax error at token "1"
```

![Screenshot from 2024-03-06 03-28-48](https://github.com/esynr3z/corsair/assets/4820969/287b1ba7-c3fc-4f33-9820-dbee6418ab99)
