### ISSUE TITLE
bugs in c header generation

### ISSUE THREAD

**Issue by v0lker** [esynr3z/corsair#25]
i haven't looked at the implementation, but i think that the padding that is generated just uses that item's lsb, forgetting to subtract how many bits have been allocated before.

e. g. in the example  https://github.com/esynr3z/corsair/blob/master/examples/regmap_yaml/regs.yaml
```
- name: DATA
    description: Data register
    address: 4
    bitfields:
    -   name: FIFO
        description: Write to push value to TX FIFO, read to get data from RX FIFO
        reset: 0
        width: 8
        lsb: 0
        access: rw
        hardware: q
        enums: []
    -   name: FERR
        description: Frame error flag. Read to clear.
        reset: 0
        width: 1
        lsb: 16
        access: rolh
        hardware: i
        enums: []
    -   name: PERR
        description: Parity error flag. Read to clear.
        reset: 0
        width: 1
        lsb: 17
        access: rolh
        hardware: i
        enums: []
```

there should be 8b of padding between `FIFO` and `FERR`, and none between `FERR` and `PERR`, presumably, but:
https://github.com/esynr3z/corsair/blob/master/examples/regmap_yaml/sw/regs.h
```
typedef struct {
    uint32_t FIFO : 8; // Write to push value to TX FIFO, read to get data from RX FIFO
    uint32_t :16; // reserved
    uint32_t FERR : 1; // Frame error flag. Read to clear.
    uint32_t :17; // reserved
    uint32_t PERR : 1; // Parity error flag. Read to clear.
} csr_data_t;
```

(i originally noticed this in a different context, where i'd have expected no padding between two items. if the above example isn't valid, please let me know and i'll update with a different one.)
